//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocatus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cocktail
    {
        public Cocktail()
        {
            this.Combinations = new HashSet<Combination>();
            this.CocktailRatings = new HashSet<CocktailRating>();
        }
    
        public int cocktail_id { get; set; }
        public string cocktail_name { get; set; }
        public string cocktail_image_path { get; set; }
    
        public virtual ICollection<Combination> Combinations { get; set; }
        public virtual ICollection<CocktailRating> CocktailRatings { get; set; }
    }
}
