//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocatus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.Combinations = new HashSet<Combination>();
        }
    
        public int ingredients_id { get; set; }
        public string type { get; set; }
        public string subtype { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Combination> Combinations { get; set; }
    }
}
