//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DerekApplication.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string company_address1 { get; set; }
        public string company_address2 { get; set; }
        public string company_zip { get; set; }
        public string company_state { get; set; }
        public string company_country { get; set; }
        public string company_phone { get; set; }
        public string company_city { get; set; }
    }
}
